import type { Inventory } from "./model.js";

export function renderMarkdown(inventory: Inventory): string {
  const lines = [
    "# Homey Inventory",
    "",
    `Generated: ${inventory.generation.timestamp}`,
    `Connection: ${inventory.connection.selected}`,
    "",
    "## Summary",
    "",
    `- Zones: ${inventory.summary.zones}`,
    `- Devices: ${inventory.summary.devices}`,
    `- Flows: ${inventory.summary.flows}`,
    `- Advanced Flows: ${inventory.summary.advanced_flows}`,
    `- Moods: ${inventory.summary.moods}`,
    "",
    "## Zones",
    "",
    ...inventory.zones.map((zone) => `- ${zone.alias}: ${zone.name}`),
    "",
    "## Devices",
    "",
    ...inventory.devices.map((device) => `- ${device.alias}: ${device.name} (${device.zone_alias ?? "unassigned"})`),
    "",
    "## Flows",
    "",
    ...inventory.flows.map((flow) => `- ${flow.alias}: ${flow.name}`),
    "",
    "## Advanced Flows",
    "",
    ...inventory.advanced_flows.map((flow) => `- ${flow.alias}: ${flow.name}`),
    "",
    "## Moods",
    "",
    ...inventory.moods.map((mood) => `- ${mood.alias}: ${mood.name}`),
    "",
    "## Warnings",
    "",
    ...(inventory.warnings.length ? inventory.warnings.map((warning) => `- ${warning}`) : ["- None"]),
    "",
    "## Privacy report",
    "",
    "- Raw IDs present: false",
    "- Secrets present: false",
    "- Redaction applied: true",
    "",
  ];
  return `${lines.join("\n")}\n`;
}
