#include "phone_provisioning.h"
#include <string.h>

static void zero_secure(void *p, size_t n){ volatile unsigned char *q=(volatile unsigned char*)p; while(n--) *q++=0; }
uint32_t phone_prov_crc32(const void *data, size_t size){ const uint8_t *p=data; uint32_t c=0xffffffffU; for(size_t i=0;i<size;i++){c^=p[i]; for(unsigned b=0;b<8;b++) c=(c>>1)^((0U-(c&1U))&0xedb88320U);} return ~c; }
void phone_prov_init(phone_prov_context_t *ctx){ if(ctx){ memset(ctx,0,sizeof(*ctx)); ctx->state=PHONE_PROV_UNPROVISIONED; } }
phone_prov_result_t phone_prov_open(phone_prov_context_t *ctx){ if(!ctx) return PHONE_PROV_ERR_ARGUMENT; if(ctx->state!=PHONE_PROV_UNPROVISIONED && ctx->state!=PHONE_PROV_REPROVISION_REQUIRED && ctx->state!=PHONE_PROV_READY) return PHONE_PROV_ERR_STATE; ctx->state=PHONE_PROV_PORTAL_ACTIVE; return PHONE_PROV_OK; }
phone_prov_result_t phone_prov_begin(phone_prov_context_t *ctx,int64_t now_s,const uint8_t r[PHONE_PROV_STATE_BYTES]){ if(!ctx||!r||now_s<0) return PHONE_PROV_ERR_ARGUMENT; if(ctx->state!=PHONE_PROV_PORTAL_ACTIVE) return PHONE_PROV_ERR_STATE; memcpy(ctx->oauth_state,r,PHONE_PROV_STATE_BYTES); ctx->issued_at_s=now_s; ctx->consumed=false; ctx->state=PHONE_PROV_AUTH_PENDING; return PHONE_PROV_OK; }
phone_prov_result_t phone_prov_complete(phone_prov_context_t *ctx,int64_t now_s,const uint8_t candidate[PHONE_PROV_STATE_BYTES],const phone_prov_provider_t *provider){
 if(!ctx||!candidate||!provider||!provider->complete)return PHONE_PROV_ERR_ARGUMENT;
 if(ctx->consumed)return PHONE_PROV_ERR_CONSUMED;
 if(ctx->state!=PHONE_PROV_AUTH_PENDING)return PHONE_PROV_ERR_STATE;
 if(now_s<ctx->issued_at_s||now_s-ctx->issued_at_s>=PHONE_PROV_SESSION_TTL_SECONDS){ctx->consumed=true;zero_secure(ctx->oauth_state,sizeof(ctx->oauth_state));return PHONE_PROV_ERR_EXPIRED;}
 unsigned diff=0;for(size_t i=0;i<PHONE_PROV_STATE_BYTES;i++)diff|=(unsigned)(ctx->oauth_state[i]^candidate[i]);if(diff)return PHONE_PROV_ERR_MISMATCH;
 ctx->consumed=true;zero_secure(ctx->oauth_state,sizeof(ctx->oauth_state));phone_prov_oauth_result_t tmp={0};phone_prov_result_t result=provider->complete(&tmp);
 if(result!=PHONE_PROV_OK){if(provider->wipe)provider->wipe(&tmp);return result;}
 if(tmp.homey_count==0U||tmp.homey_count>PHONE_PROV_MAX_HOMEYS){if(provider->wipe)provider->wipe(&tmp);return PHONE_PROV_ERR_STALE;}
 for(size_t i=0;i<tmp.homey_count;i++)for(size_t j=i+1;j<tmp.homey_count;j++)if(strcmp(tmp.homeys[i].id,tmp.homeys[j].id)==0){if(provider->wipe)provider->wipe(&tmp);return PHONE_PROV_ERR_DUPLICATE;}
 ctx->result=tmp;zero_secure(&tmp,sizeof(tmp));ctx->state=PHONE_PROV_HOMEY_SELECTION_REQUIRED;return PHONE_PROV_OK;
}
phone_prov_result_t phone_prov_select(phone_prov_context_t *ctx,const char *id,phone_prov_record_v1_t *rec,uint32_t gen){ if(!ctx||!id||!rec) return PHONE_PROV_ERR_ARGUMENT; if(ctx->state!=PHONE_PROV_HOMEY_SELECTION_REQUIRED) return PHONE_PROV_ERR_STATE; const phone_prov_homey_t *h=NULL; for(size_t i=0;i<ctx->result.homey_count;i++) if(strcmp(ctx->result.homeys[i].id,id)==0){ if(h) return PHONE_PROV_ERR_DUPLICATE; h=&ctx->result.homeys[i]; } if(!h) return PHONE_PROV_ERR_STALE; memset(rec,0,sizeof(*rec)); rec->magic=PHONE_PROV_RECORD_MAGIC; rec->schema_version=PHONE_PROV_RECORD_VERSION; rec->payload_size=(uint16_t)sizeof(*rec); rec->generation=gen; rec->expires_at=ctx->result.expires_at; rec->discovery_strategy=1U; memcpy(rec->access_token,ctx->result.access_token,sizeof(rec->access_token)); memcpy(rec->refresh_token,ctx->result.refresh_token,sizeof(rec->refresh_token)); memcpy(rec->homey_id,h->id,sizeof(rec->homey_id)); memcpy(rec->homey_name,h->name,sizeof(rec->homey_name)); rec->payload_crc32=0; rec->payload_crc32=phone_prov_crc32(rec,sizeof(*rec)); return PHONE_PROV_OK; }
bool phone_prov_publication_readback_valid(const phone_prov_record_v1_t *expected,const phone_prov_record_v1_t *actual,bool present){return expected&&actual&&present&&phone_prov_record_valid(expected)&&phone_prov_record_valid(actual)&&memcmp(expected,actual,sizeof(*expected))==0;}
bool phone_prov_record_valid(const phone_prov_record_v1_t *r){ if(!r||r->magic!=PHONE_PROV_RECORD_MAGIC||r->schema_version!=PHONE_PROV_RECORD_VERSION||r->payload_size!=sizeof(*r)||!r->access_token[0]||!r->refresh_token[0]||!r->homey_id[0]||!r->homey_name[0]) return false; phone_prov_record_v1_t t=*r; uint32_t expected=t.payload_crc32; t.payload_crc32=0; return expected==phone_prov_crc32(&t,sizeof(t)); }
phone_prov_result_t phone_prov_change(phone_prov_context_t *ctx){ if(!ctx||ctx->state!=PHONE_PROV_READY) return PHONE_PROV_ERR_STATE; ctx->state=PHONE_PROV_HOMEY_SELECTION_REQUIRED; return PHONE_PROV_OK; }
phone_prov_result_t phone_prov_change_refresh(phone_prov_context_t *ctx,const phone_prov_provider_t *provider){ if(!ctx||!provider||!provider->complete) return PHONE_PROV_ERR_ARGUMENT; if(ctx->state!=PHONE_PROV_READY) return PHONE_PROV_ERR_STATE; phone_prov_oauth_result_t refreshed={0}; phone_prov_result_t r=provider->complete(&refreshed); if(r!=PHONE_PROV_OK){if(provider->wipe)provider->wipe(&refreshed);return r;} if(refreshed.homey_count==0U||refreshed.homey_count>PHONE_PROV_MAX_HOMEYS){if(provider->wipe)provider->wipe(&refreshed);return PHONE_PROV_ERR_STALE;} for(size_t i=0;i<refreshed.homey_count;i++) for(size_t j=i+1;j<refreshed.homey_count;j++) if(strcmp(refreshed.homeys[i].id,refreshed.homeys[j].id)==0){if(provider->wipe)provider->wipe(&refreshed);return PHONE_PROV_ERR_DUPLICATE;} zero_secure(&ctx->result,sizeof(ctx->result)); ctx->result=refreshed; zero_secure(&refreshed,sizeof(refreshed)); ctx->state=PHONE_PROV_HOMEY_SELECTION_REQUIRED; return PHONE_PROV_OK; }
void phone_prov_wipe_context(phone_prov_context_t *ctx){ if(ctx){zero_secure(ctx,sizeof(*ctx));ctx->state=PHONE_PROV_UNPROVISIONED;} }
